// Access Medical Labs portal scraper.
//
// Target: https://access.labsvc.net/labgen/ (Sencha ExtJS portal, NOT accessmedlab.com)
// Selectors captured 2026-05-21. See docs/ACCESS_PORTAL_CAPTURE.md.
//
// ExtJS generates dynamic IDs (e.g. textfield-1050) that change between sessions.
// Always select by placeholder, class, or text content. Never by autogenerated id.

import type { Browser, Page } from "playwright";
import type { OpenCase } from "../tracker-client.js";
import type { LabScraper, ScrapeRun, ScrapeResult } from "./base.js";

const ACCESS_LOGIN_URL = "https://access.labsvc.net/labgen/";
const USERNAME = process.env.ACCESS_USERNAME;
const PASSWORD = process.env.ACCESS_PASSWORD;

// Module-level PDF capture slot. The ctx.route handler installed in run()
// fulfills this whenever the next +repdown POST returns application/pdf.
// downloadRowPdf arms it before clicking Print, then awaits. We intercept
// at the network layer because Chrome's built-in PDF viewer extension
// rewrites application/pdf response bodies into a viewer-wrapper HTML
// before Playwright's response.body() can read them.
let pendingPdfCapture:
  | { resolve: (v: { buf: Buffer; url: string }) => void; reject: (e: Error) => void }
  | null = null;

type RowSnapshot = {
  name: string;          // "LAST, FIRST"
  dob: string;           // MM/DD/YYYY
  accession: string;     // 8-digit, may have trailing space
  collectionDate: string;
  finalDate: string;
  status: string;        // "Complete" / "Incomplete"
};

export const accessScraper: LabScraper = {
  labName: "Access",

  async run(browser: Browser, openCases: OpenCase[]): Promise<ScrapeRun> {
    if (!USERNAME || !PASSWORD) {
      throw new Error("ACCESS_USERNAME / ACCESS_PASSWORD not configured");
    }
    if (openCases.length === 0) return { found: [], errors: [] };

    const ctx = await browser.newContext({ acceptDownloads: true });

    await ctx.route(
      (url) => url.toString().includes("+repdown"),
      async (route, request) => {
        if (request.method() !== "POST") {
          return route.continue();
        }
        try {
          const resp = await route.fetch();
          const body = await resp.body();
          const contentType = resp.headers()["content-type"] ?? "";
          if (contentType.includes("application/pdf") && pendingPdfCapture) {
            pendingPdfCapture.resolve({ buf: Buffer.from(body), url: request.url() });
            pendingPdfCapture = null;
          }
          await route.fulfill({ response: resp, body });
        } catch (err) {
          if (pendingPdfCapture) {
            pendingPdfCapture.reject(err as Error);
            pendingPdfCapture = null;
          }
          await route.abort().catch(() => {});
        }
      },
    );

    const page = await ctx.newPage();

    // labgen sets window.onbeforeunload = "Your work will be lost!" — auto-dismiss.
    page.on("dialog", (d) => d.accept().catch(() => {}));

    const found: ScrapeResult[] = [];
    const errors: ScrapeRun["errors"] = [];

    try {
      await login(page);
      await openInbox(page);
      const rows = await readInboxRows(page);

      for (const c of openCases) {
        try {
          const match = matchRow(c, rows);
          if (!match) continue;
          if (!isReady(match)) continue;

          const pdf = await downloadRowPdf(page, match.accession);
          if (!pdf) continue;

          found.push({
            caseId: c.caseId,
            labExternalRef: match.accession.trim(),
            pdfBase64: pdf.base64,
            pdfFilename: pdf.filename,
            resultIssuedAt: parseFinalDate(match.finalDate),
          });
        } catch (err) {
          errors.push({
            caseId: c.caseId,
            message: err instanceof Error ? err.message : String(err),
          });
        }
      }
    } finally {
      await ctx.close();
    }

    return { found, errors };
  },
};

async function login(page: Page): Promise<void> {
  await page.goto(ACCESS_LOGIN_URL, { waitUntil: "networkidle" });
  await page.fill('input[placeholder="User ID"]', USERNAME!);
  await page.fill('input[placeholder="Password"]', PASSWORD!);
  // ExtJS login button: <a class="x-btn"> with an icon child of class "icon-login".
  await page.click("a.x-btn:has(.icon-login)");
  // Successful login surfaces the left-nav Inbox tile.
  await page.waitForSelector("#maininbox", { state: "visible", timeout: 15000 });
}

async function openInbox(page: Page): Promise<void> {
  await page.click("#maininbox");
  // Inbox grid renders rows into table.x-grid-item.
  await page.waitForSelector("table.x-grid-item[data-recordid]", { timeout: 15000 });
}

async function readInboxRows(page: Page): Promise<RowSnapshot[]> {
  // Iterate with locators rather than $$eval — tsx/esbuild injects a __name
  // helper that breaks when callbacks are serialized into the browser context.
  // One call per cell is slower but reliable across runtimes.
  //
  // Column order (1-indexed): 1=checkbox, 2=name, 3=dob, 4=acc#, 5=ser dt,
  // 6=col dt, 7=final dt, 8=phys, 9=status, 10=validity, 11=tests
  const rowHandles = await page.locator("table.x-grid-item[data-recordid]").all();
  const out: RowSnapshot[] = [];
  for (const t of rowHandles) {
    const tds = t.locator("tr > td");
    const cell = async (i: number) => ((await tds.nth(i).textContent()) ?? "").trim();
    out.push({
      name: await cell(1),
      dob: await cell(2),
      accession: await cell(3),
      collectionDate: await cell(5),
      finalDate: await cell(6),
      status: await cell(8),
    });
  }
  return out;
}

function isReady(row: RowSnapshot): boolean {
  // "Complete" + non-empty Final Dt is the canonical ready signal.
  return row.status.toLowerCase().includes("complete") && row.finalDate.length > 0;
}

function matchRow(c: OpenCase, rows: RowSnapshot[]): RowSnapshot | null {
  // O(1) by stored accession if we've matched this case before.
  if (c.labExternalRef) {
    const byRef = rows.find((r) => r.accession.trim() === c.labExternalRef);
    if (byRef) return byRef;
  }
  // First-time match: patient name + DOB. Access displays "LAST, FIRST".
  const dobNorm = normalizeDob(c.patientDob);
  const nameNorm = normalizeName(c.patientName);
  return (
    rows.find(
      (r) => normalizeName(r.name) === nameNorm && normalizeDob(r.dob) === dobNorm,
    ) ?? null
  );
}

function normalizeName(s: string): string {
  // "Doe, Jane" / "DOE, JANE" / "Jane Doe" all → "doe jane"
  const clean = s.replace(/[^a-zA-Z, ]/g, "").trim().toLowerCase();
  if (clean.includes(",")) {
    const [last, first] = clean.split(",").map((p) => p.trim());
    return `${last} ${first}`.trim();
  }
  const parts = clean.split(/\s+/);
  if (parts.length >= 2) return `${parts[parts.length - 1]} ${parts[0]}`;
  return clean;
}

function normalizeDob(s: string | null): string {
  if (!s) return "";
  // Tracker stores ISO (YYYY-MM-DD); Access shows MM/DD/YYYY. Normalize to YYYY-MM-DD.
  const iso = s.match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (iso) return `${iso[1]}-${iso[2]}-${iso[3]}`;
  const us = s.match(/^(\d{2})\/(\d{2})\/(\d{4})/);
  if (us) return `${us[3]}-${us[1]}-${us[2]}`;
  return s.trim();
}

function parseFinalDate(s: string): string | undefined {
  // "05/21/26" or "05/21/2026" → ISO date string.
  const m = s.match(/^(\d{2})\/(\d{2})\/(\d{2,4})$/);
  if (!m) return undefined;
  const year = m[3].length === 2 ? `20${m[3]}` : m[3];
  return `${year}-${m[1]}-${m[2]}`;
}

async function downloadRowPdf(
  page: Page,
  accession: string,
): Promise<{ base64: string; filename: string } | null> {
  // Find the row whose Acc# cell matches.
  const accClean = accession.trim();
  const row = page.locator(`table.x-grid-item[data-recordid]`, {
    has: page.locator(`td:nth-child(4)`, { hasText: accClean }),
  });
  if ((await row.count()) === 0) return null;

  // Click the row checkbox (.x-grid-row-checker is inside the first td).
  await row.first().locator(".x-grid-row-checker").click();

  // Find "Print Selected reports" button by visible text (id is dynamic).
  const printBtn = page.locator('a.x-btn:has-text("Print Selected reports")').first();
  const ctx = page.context();

  // Arm the network-layer PDF capture, then click. The ctx.route handler in
  // run() resolves capturePromise with the real PDF bytes as soon as the
  // matching +repdown POST returns — bypassing Chrome's PDF viewer extension
  // which would otherwise rewrite the response body. We still let the popup
  // open and close it after, for clean session state.
  const capturePromise = new Promise<{ buf: Buffer; url: string }>((resolve, reject) => {
    pendingPdfCapture = { resolve, reject };
    setTimeout(() => {
      if (pendingPdfCapture) {
        pendingPdfCapture = null;
        reject(new Error(`timeout capturing PDF for acc ${accClean}`));
      }
    }, 60_000);
  });

  const popupPromise = ctx.waitForEvent("page", { timeout: 60_000 });
  await printBtn.click();
  const popup = await popupPromise.catch(() => null);

  const { buf } = await capturePromise;
  if (popup) await popup.close().catch(() => {});

  // Deselect for the next iteration so we don't combine PDFs.
  await row.first().locator(".x-grid-row-checker").click();

  return {
    base64: buf.toString("base64"),
    filename: `access_${accClean}.pdf`,
  };
}
