// One-off pipeline test: build a mock Access-style lab report PDF for the
// test patient Alex Moran (alex@centnerhb.com, collected today) and email it
// to labs@centnerhb.com via Resend — the same proven sender the Kennedy
// Krieger auto-forward uses. The Gmail poller then ingests → parses → matches
// it like any real lab email. Sends ONE email; touches nothing else.
//
// Run from the repo root:
//   npx tsx --env-file=.env.local scripts/send-mock-lab-email.ts
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { Resend } from "resend";

const TO = "labs@centnerhb.com";
const PATIENT = "Alex Moran";
const PATIENT_EMAIL = "alex@centnerhb.com";

function todayInMiami(): string {
  return new Date().toLocaleDateString("en-CA", { timeZone: "America/New_York" });
}

async function buildMockReport(collected: string): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([612, 792]); // US Letter
  const helv = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const mono = await doc.embedFont(StandardFonts.Courier);

  let y = 740;
  const draw = (text: string, opts: { font?: typeof helv; size?: number } = {}) => {
    page.drawText(text, {
      x: 54,
      y,
      size: opts.size ?? 11,
      font: opts.font ?? helv,
      color: rgb(0.1, 0.1, 0.12),
    });
    y -= (opts.size ?? 11) + 7;
  };

  draw("ACCESS MEDICAL LABS", { font: bold, size: 18 });
  draw("FINAL REPORT", { font: bold, size: 12 });
  y -= 10;
  draw(`Patient Name: ${PATIENT}`);
  draw(`Patient Email: ${PATIENT_EMAIL}`);
  draw(`Accession #: TEST-${collected.replace(/-/g, "")}`);
  draw(`Date Collected: ${collected}`);
  draw(`Date Reported: ${collected}`);
  draw("Ordering Provider: Centner Wellness");
  draw("Panel: Comprehensive Metabolic Panel");
  y -= 14;
  draw("Test                Result          Reference Range", { font: mono, size: 10 });
  draw("Glucose             88 mg/dL        65-99", { font: mono, size: 10 });
  draw("BUN                 14 mg/dL        7-25", { font: mono, size: 10 });
  draw("Creatinine          0.95 mg/dL      0.60-1.35", { font: mono, size: 10 });
  draw("Sodium              140 mmol/L      135-146", { font: mono, size: 10 });
  draw("Potassium           4.2 mmol/L      3.5-5.3", { font: mono, size: 10 });
  draw("ALT                 22 U/L          9-46", { font: mono, size: 10 });
  draw("AST                 24 U/L          10-40", { font: mono, size: 10 });
  y -= 24;
  draw("*** MOCK REPORT — generated by the lab-tracker pipeline test. Not a real result. ***", {
    size: 9,
  });

  return Buffer.from(await doc.save());
}

async function main() {
  const apiKey = process.env.RESEND_API_KEY;
  const fromEmail = process.env.ALERT_FROM_EMAIL;
  if (!apiKey || !fromEmail) {
    throw new Error("RESEND_API_KEY / ALERT_FROM_EMAIL not set — run with --env-file=.env.local");
  }

  const collected = todayInMiami();
  const pdf = await buildMockReport(collected);

  const resend = new Resend(apiKey);
  const { data, error } = await resend.emails.send({
    from: `Centner Wellness <${fromEmail}>`,
    to: [TO],
    subject: `Lab Results - ${PATIENT} (pipeline test)`,
    text:
      `Final report attached for ${PATIENT}, collected ${collected}.\n\n` +
      `(Mock report — lab-tracker inbox pipeline test.)`,
    attachments: [
      {
        filename: `access_${PATIENT.toLowerCase().replace(/ /g, "_")}_${collected}.pdf`,
        content: pdf,
      },
    ],
  });
  if (error) throw new Error(`Resend send failed: ${JSON.stringify(error)}`);
  console.log(
    `Sent to ${TO} — Resend id ${data?.id}, collected ${collected}, pdf ${pdf.length} bytes`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
